default_stages: [commit]
repos:
  - repo: https://github.com/yyang-pplus/config-sh.git
    rev: 768419ca1741aaabf49664ddb561071a74680cbe
    hooks:
      - id: astyle-c-in
      - id: shfmt

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.3
    hooks:
      - id: clang-format

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [commit]
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: trailing-whitespace
        stages: [commit]

      # Python only
      - id: debug-statements

  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
      - id: cmake-lint

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950
    hooks:
      - id: mypy

  - repo: https://github.com/klieret/jekyll-relative-url-check
    rev: v2.0.1
    hooks:
      - id: jekyll-relative-url-check-html
      - id: jekyll-relative-url-check-markdown

  - repo: https://github.com/markdownlint/markdownlint.git
    rev: v0.11.0
    hooks:
      - id: markdownlint
